### ISSUE TITLE
NoData value

### ISSUE THREAD

**Issue by luji1515** [ASFHyP3/ASFHyP3.github.io#2]
I want to know why is there a lot of NoData value in my D-InSAR result image

**Comment by talogan** [comment]
@luji1515  Thank you for your question.  It is difficult to say why there are a lot of NoData values in your D-InSAR results without being able to look at those results.  They could be the result of terrain geometry (radar shadow or radar layover), temporal decorrelation or, possibly, due to the presence of water in the scene being processed.

 If you can share the product bundle with us (or just the granule ID), we can investigate what you are seeing.

**Comment by talogan** [comment]
@luji1515 We have found the granules that you ran through hyp3.  They seem to be in the mountains in northern China.  The dark plateau, I assume, is the region you are referring to.  The backscatter in this area is very low.  

Any pixels with intensity < backscatter * 0.2 are filtered out during phase unwrapping using our current settings.  So, this explains why there are NoData values in your InSAR unwrapped phase.

We are examining these settings to see if they can be improved.
